M48
; DRILL file KiCad 10.0.6 date 2026-09-26T14:50:12
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-26T14:50:12+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.400
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X88.4Y19.75
T2
X5.0Y95.0
X5.0Y5.0
X101.0Y95.0
X101.0Y5.0
M30
