"""Explicit local control routes; geometric clearance screening, not KiCad DRC."""
from design_d2 import *
import sys
sys.path.insert(0,str(BASE/'work/geometry_lib'))
from shapely.geometry import box,Polygon,LineString
d=OUT/'UMI_USB_D2';path=d/'UMI_USB_D2.kicad_pcb';b=parse(path.read_text())
netcodes={str(a[2]):str(a[1]) for a in all_(b,'net')};pads=[];lookup={}
for f in all_(b,'footprint'):
 ref=str(prop(f,'Reference')[2]);ox,oy=map(float,one(f,'at')[1:3])
 for p in all_(f,'pad'):
  if not any(str(v).endswith('.Cu') for v in one(p,'layers')[1:]):continue
  x,y=map(float,one(p,'at')[1:3]);x+=ox;y+=oy;w,h=map(float,one(p,'size')[1:3]);n=one(p,'net');net=str(n[2]) if n else None
  shape=box(x-w/2,y-h/2,x+w/2,y+h/2)
  if p[3]=='custom':
   for g in one(p,'primitives')[1:]:
    if g[0]=='gr_poly':shape=shape.union(Polygon([(x+float(v[1]),y+float(v[2])) for v in one(g,'pts')[1:]]))
  pads.append((ref+'.'+str(p[1]),net,shape));lookup[(ref,str(p[1]))]=(x,y)
def at(ref,pin):return lookup[(ref,str(pin))]
routes=[
 ('BOOT',.25,[at('U1',2),at('U1',3)]),
 ('FB',.2,[at('R7',2),(36.05,19.225),(36.05,20.45),at('U1',8)]),
 ('FB',.2,[at('R1',1),(35.775,20.55),(36.05,20.45)]),
 ('RT',.2,[at('U1',12),(43.8,19.8),(44,20),at('R8',1)]),
 ('PG',.2,[at('U1',13),(43.75,19.15),(44.35,18.55),(48.1,18.55),(48.1,22.3),at('R9',2)]),
]
for port,x in [(1,24),(2,57)]:
 u='U'+str(port+1);r='R'+str(port+1);fault='R'+str(port+3)
 routes.extend([
  ('ILIM'+str(port),.2,[at(u,5),(x+2.7,22.975),(x+3.675,22),at(r,1)]),
  ('FAULT'+str(port),.2,[at(u,8),(x+2.3,20.175),(x+5.825,20.175),at(fault,2)])])
shapes=[];errors=[]
for i,(net,width,points) in enumerate(routes):
 shape=LineString(points).buffer(width/2)
 for name,pnet,padshape in pads:
  if pnet!=net and shape.distance(padshape)<.1999:errors.append(f'{net} route {i} is too close to {name}: {shape.distance(padshape):.3f} mm')
 for othernet,othershape in shapes:
  if othernet!=net and shape.distance(othershape)<.1999:errors.append(f'{net} is too close to route on {othernet}')
 shapes.append((net,shape))
if errors:raise SystemExit('\n'.join(errors))
# Re-running replaces just the deterministic segments generated by this script.
new=[]
for i,(net,width,points) in enumerate(routes):
 for j,(a,z) in enumerate(zip(points,points[1:])):
  new.append(parse(f'(segment (start {a[0]} {a[1]}) (end {z[0]} {z[1]}) (width {width}) (layer "F.Cu") (net {netcodes[net]}) (uuid "{uid("local-route/"+str(i)+"/"+str(j))}"))'))
newids={one(s,'uuid')[1] for s in new}
b[:]=[a for a in b if not(isinstance(a,list) and a[0]=='segment' and one(a,'uuid')[1] in newids)]
b.extend(new);write(path,b)
(d/'local_route_screen.json').write_text(json.dumps(dict(scope='Local F.Cu control routes only; geometric screening is not DRC',segments=len(new),minimum_screened_clearance_mm=.2,screen_errors=errors,power_routing_complete=False,ground_routing_complete=False),indent=2))
print(f'Wrote {len(new)} screened local control segments. Power and ground routing remain incomplete.')
