from pathlib import Path
import json
c=470e-12;r=7.5;v=53.518163;f=9e9/40200
x={'R1':{'recommendation':'RC2010JK-077R5L is stocked prototype candidate; published nanosecond repetitive-pulse equivalence not established','mpn':'RC2010JK-077R5L','jlc':'C4169838','stock':220,'order_quantity_field':220,'value_ohm':7.5,'tolerance_percent':5,'power_W':.75,'package':'2010','changes_to_PCB':'none proposed','original_lifecycle':'Panasonic primary page NRFND'},'snubber':{'C1_F':c,'C1_nets':['SW','SNUB'],'R1_nets':['SNUB','BOOST_OUT'],'fsw_Hz':f,'RC_s':r*c,'nominal_P_W':c*v*v*f,'upper_static_P_W':c*54.159133**2*f,'nominal_energy_per_edge_J':.5*c*v*v,'ideal_step_peak_W':v*v/r,'qualification':'estimate excludes switching rise time/parasitics/ringing; average rating does not alone prove pulse endurance'},'C1':{'recommendation':'retain existing KEMET C0805C471J1GACTU pending reservation/attrition confirmation','stock_previous_snapshot':15,'needed':10,'reason':'No proven higher-stock same-tolerance alternative established; 50V substitutes rejected;10/20% tolerance alternatives not adopted'},'L1':{'recommendation':'retain Coilcraft SER2915H-103KL','stock_previous_snapshot':17,'needed':10,'reason':'Ten plus some margin possible; reserve/fixture approval required. Different magnetic introduces DCR/saturation/loss/geometry risk.'}}
Path('work/d6_electrical_resolution.json').write_text(json.dumps(x,indent=2))
Path('work/d6_electrical_resolution.md').write_text('''# D6 electrical sourcing resolution

No PCB changes made. The concrete R1 candidate is **Yageo RC2010JK-077R5L, JLC C4169838**, live220 stock and220 available-order field. It matches7.5Ω±5%,0.75W,2010 general-purpose thick film. Panasonic original ERJ12ZYJ7R5U is explicitly NRFND on its primary product page and is also general purpose, not a special pulse family. Alternative1% YageoRC2010FK-077R5L C877612 has37stock/20order-field, offering less headroom.

The candidate is reasonable for engineering prototype evaluation with unchanged footprint. **Equal/better published repetitive-pulse endurance has not been established**, so this report does not assert that procurement alone qualifies its snubber use. This is a documentary limitation, not a claim that the candidate is known to fail. Do not describe it as a proven pulse-rated drop-in.

Circuit: C1=470pF100V,SW–SNUB;R1=7.5Ω,SNUB–BOOST_OUT. RT40.2kΩ gives223.88kHz from TI equation. Ideal full-swing average P=C·V²·f=0.3014W at53.518V,0.3086W at54.159V, below0.75W. Adding5% capacitance and10% frequency as an illustrative bound gives~0.356W (frequency bound illustrative, not a claimed datasheet limit). RC=3.525ns; ideal instantaneous step peaks~382W and7.14A, with~0.673µJ per edge. Real rise time/parasitics modify the pulse. Published general-purpose continuous-power or seconds-long overload ratings cannot alone validate nanosecond repetitive peaks; matching ringing, resistor temperature and pulse endurance remains the same engineering test obligation as the original untested design.

C1: retain existing KEMET470pF100VC0G5%0805 with fifteen previously observed pieces for ten boards, subject to actual reservation and attrition. Search foundC599927 KEMET470pF100V but10% tolerance and other50V entries; no fully verified better-stock exact-electrical alternative was established. Do not adopt50V for the53.5V snubber.

L1: retain CoilcraftSER2915H-103KL,17 previously observed stock/16order-field. It covers ten before reservation and agreed attrition. No alternate magnetics are recommended merely to increase stock margin: saturation,DCR,AC loss and fit affect the conversion stage. Fixture acceptance remains required. Exact part preorder/restock is the least electrical-risk solution if stock cannot be reserved.

Sources: [Panasonic original](https://industrial.panasonic.com/ww/products/pt/general-purpose-chip-resistors/models/ERJ12ZYJ7R5U), [JLC candidate](https://jlcpcb.com/partdetail/YAGEO-RC2010JK077R5L/C4169838), [JLC1% option](https://jlcpcb.com/partdetail/YAGEO-RC2010FK077R5L/C877612), [manufacturer RC family document mirrored by LCSC](https://datasheet.lcsc.com/lcsc/YAGEO-RC2010JK-070RL_C152156.pdf), [TI LM5122](https://www.ti.com/lit/ds/symlink/lm5122.pdf), [Coilcraft L1](https://www.coilcraft.com/en-us/products/power/shielded-inductors/high-current-flat-wire/ser/ser29xx/ser2915h-103/).
''',encoding='utf8')
print(x['snubber'])
