M48
; DRILL file KiCad 10.0.6 date 2026-09-26T14:49:11
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-26T14:49:11+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.400
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.500
%
G90
G05
T1
X13.4Y63.014
X13.4Y42.014
X34.0Y21.014
X46.4Y63.014
X46.4Y42.014
T2
X8.0Y92.264
X8.0Y8.0
X60.0Y92.264
X60.0Y8.0
M30
